[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle the .well-known directory correctly
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"

# Specific header for assetlinks.json to ensure proper content-type
[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

# Add headers for article pages to help with deep linking
[[headers]]
  for = "/article/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Simple redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# Ensure assetlinks.json is accessible
[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/.well-known/assetlinks.json"
  status = 200

# Handle article pages - more specific rule first
[[redirects]]
  from = "/article/:id"
  to = "/.netlify/functions/next/article/:id"
  status = 200
  force = true

# Fallback for article pages
[[redirects]]
  from = "/article/*"
  to = "/.netlify/functions/next/article/[id]"
  status = 200
  force = true