[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle the .well-known directory correctly
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

# Simple redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# Ensure assetlinks.json is accessible
[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/.well-known/assetlinks.json"
  status = 200